version:  "3.8"
services:
  front-end: 
    build: ../Front-end
    container_name: Front-end_c
    ports:
      - '5173:5173'
  back-end: 
    build: ../Back-end
    container_name: Back-end_c
    ports: 
      - '8000:8000'
