version:  "3.8"
services:
  front-end: 
    build: ../Front-end
    container_name: Front-end_c
    ports:
      - '5173:5173'
    volumes:
      - ../Front-end:/app
      - /app/node_modules
  back-end: 
    build: ../Back-end
    container_name: Back-end_c
    ports: 
      - '8000:8000'
    volumes:
      - ../Back-end:/app
      - /app/node_modules
      